# Generated by Django 3.0.3 on 2020-02-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='upload_datetime',
            new_name='created',
        ),
    ]
